language: 'en'
delimiter: ' -> ' #player -> player: [message]

message:
  en:
    errorMessage: '[PM] use: /pm [recipient] [message]'
    playerNotFound: '[PM] Player not Found'
    tag: '[whisper]'
  ru:
    errorMessage: '[PM] используйте: /pm [Приниматель] [текст сообщения]'
    playerNotFound: '[PM] Игрока нету на сервере'
    tag: '[шёпот]'

pmColor: 'GRAY'

# AQUA
# BLACK
# BLUE
# BOLD
# DARK_AQUA
# DARK_BLUE
# DARK_GRAY
# DARK_GREEN
# DARK_PURPLE
# DARK_RED
# GOLD
# GRAY
# GREEN
# ITALIC
# LIGHT_PURPLE
# MAGIC
# RED
# WHITE
# YELLOW
# UNDERLINE